runtime: go111

includes:
- secrets.yaml

handlers:

- url: /inviter/static
  static_dir: inviter/static
  secure: always
  redirect_http_response_code: 301
  http_headers:
      Access-Control-Allow-Origin: '*'

- url: /css
  static_dir: blog/public/css
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Access-Control-Allow-Origin: '*'

- url: /fonts
  static_dir: blog/public/fonts
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Access-Control-Allow-Origin: '*'

- url: /js
  static_dir: blog/public/js
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Access-Control-Allow-Origin: '*'

- url: /img
  static_dir: blog/public/img
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Access-Control-Allow-Origin: '*'

- url: /images
  static_dir: blog/public/images
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Access-Control-Allow-Origin: '*'

- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
