baseURL = "https://frenchgo.fr/"
languageCode = "fr-FR"
title = "frenchgo.fr /ˈɡoʊfər/"
theme = "hugo-theme-cactus-plus"
googleAnalytics = "UA-48359234-3"

removePathAccents = true

[permalinks]
  post = "/:year/:month/:title/"

[params]
	name = "frenchgo.fr /ˈɡoʊfər/"
	description = "Blog français sur Go"

	# Enter optionally your twitter account
	twitter = "frenchgofr"
	enableRSS = true

	# Disqus comment
	disqusShortname = "frenchgofr"
	# Disable disqus comments by set `enableDisqus = "false"`
	enableDisqus = true

	# Enable googleAnalytics
    enableGoogleAnalytics = true

    enableRobotsTXT = true

    # The variables below are optionally too and can be used to
    # translate or customize each string of the theme.

    # Navigation links
    home = "Accueil"
    about = "A propos"
    archive = "Archives"
    subscribe = "RSS"
    tags = "Tags"
    # Pagination links
    olderPosts = "Articles précédents"
    newerPosts = "Articles suivants"
    readMore = "En savoir plus"
    # 404 page
    title404 = "Page introuvable"
    subtitle404 = "On fera mieux le prochain coup"

    # Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
    iconFont = "font-awesome"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "rounded"

# Add additional social link entries underneath
[social]
    twitter-square = "https://twitter.com/frenchgofr"
    github-square = "https://github.com/frenchgofr"
